// sampleData.js
export const SAMPLE_LOCATIONS = [
  {
    id: "1",
    name: "Marine Drive",
    description: "A scenic boulevard along the coastline, perfect for evening strolls.",
    coordinates: { lat: 18.944703, lng: 72.823551 },
    tags: ["nature", "recreation"],
    badges: ["Popular"],
    category: "Parks",
    status: "Open Now",
    rating: 4.9,
  },
  {
    id: "2",
    name: "Gateway of India",
    description: "Iconic arch-monument built during the 20th century in Mumbai.",
    coordinates: { lat: 18.9220, lng: 72.8347 },
    tags: ["landmark", "history"],
    badges: ["Heritage"],
    category: "Landmarks",
    status: "Open Now",
    rating: 4.8,
  },
  {
    id: "3",
    name: "Chhatrapati Shivaji Maharaj Terminus",
    description: "Historic railway station and UNESCO World Heritage Site.",
    coordinates: { lat: 18.9402, lng: 72.8356 },
    tags: ["history", "architecture"],
    badges: ["Heritage"],
    category: "Landmarks",
    status: "Open Now",
    rating: 4.7,
  },
  {
    id: "4",
    name: "Juhu Beach",
    description: "Popular beach known for its street food and sunset views.",
    coordinates: { lat: 19.0880, lng: 72.8267 },
    tags: ["nature", "food"],
    badges: ["Family Friendly"],
    category: "Parks",
    status: "Open Now",
    rating: 4.6,
  },
  {
    id: "5",
    name: "Elephanta Caves",
    description: "Caves with ancient sculptures and carvings, accessible by ferry.",
    coordinates: { lat: 18.9634, lng: 72.9313 },
    tags: ["history", "landmark"],
    badges: ["Heritage"],
    category: "Landmarks",
    status: "Closed",
    rating: 4.5,
  },
  {
    id: "6",
    name: "Colaba Causeway",
    description: "Bustling street with shops and eateries offering unique items.",
    coordinates: { lat: 18.9220, lng: 72.8326 },
    tags: ["shopping", "food"],
    badges: ["Tourist Favorite"],
    category: "Shopping",
    status: "Open Now",
    rating: 4.5,
  },
  {
    id: "7",
    name: "Siddhivinayak Temple",
    description: "Famous temple dedicated to Lord Ganesha.",
    coordinates: { lat: 19.0173, lng: 72.8305 },
    tags: ["religious", "landmark"],
    badges: ["Spiritual"],
    category: "Religious",
    status: "Open Now",
    rating: 4.9,
  },
  {
    id: "8",
    name: "Haji Ali Dargah",
    description: "Island mosque and dargah built in honor of Pir Haji Ali Shah Bukhari.",
    coordinates: { lat: 18.9823, lng: 72.8090 },
    tags: ["religious", "architecture"],
    badges: ["Spiritual"],
    category: "Religious",
    status: "Open Now",
    rating: 4.8,
  },
  {
    id: "9",
    name: "Bandra Worli Sea Link",
    description: "Cable-stayed bridge connecting Bandra and Worli.",
    coordinates: { lat: 19.0415, lng: 72.8170 },
    tags: ["architecture", "landmark"],
    badges: ["Iconic"],
    category: "Landmarks",
    status: "Open Now",
    rating: 4.7,
  },
  {
    id: "10",
    name: "Powai Lake",
    description: "Artificial lake offering serene views and bird watching.",
    coordinates: { lat: 19.1222, lng: 72.9045 },
    tags: ["nature", "recreation"],
    badges: ["Serene"],
    category: "Parks",
    status: "Open Now",
    rating: 4.6,
  },
  {
    id: "11",
    name: "Phoenix Marketcity",
    description: "Large shopping mall with international brands and entertainment options.",
    coordinates: { lat: 19.0867, lng: 72.8895 },
    tags: ["shopping", "entertainment"],
    badges: ["Popular"],
    category: "Shopping",
    status: "Open Now",
    rating: 4.7,
  },
  {
    id: "12",
    name: "Kanheri Caves",
    description: "Ancient Buddhist caves located in the Sanjay Gandhi National Park.",
    coordinates: { lat: 19.2167, lng: 72.9101 },
    tags: ["history", "nature"],
    badges: ["Heritage"],
    category: "Landmarks",
    status: "Open Now",
    rating: 4.8,
  },
  {
    id: "13",
    name: "EsselWorld",
    description: "Large amusement park with rides and attractions for all ages.",
    coordinates: { lat: 19.2367, lng: 72.8051 },
    tags: ["entertainment", "recreation"],
    badges: ["Family Friendly"],
    category: "Entertainment",
    status: "Open Now",
    rating: 4.6,
  },
  {
    id: "14",
    name: "Global Vipassana Pagoda",
    description: "Meditation hall and pagoda promoting Vipassana meditation.",
    coordinates: { lat: 19.2096, lng: 72.8745 },
    tags: ["religious", "architecture"],
    badges: ["Spiritual"],
    category: "Religious",
    status: "Open Now",
    rating: 4.8,
  },
  {
    id: "15",
    name: "Nehru Science Centre",
    description: "Science museum featuring interactive exhibits and a planetarium.",
    coordinates: { lat: 19.0183, lng: 72.8315 },
    tags: ["education", "entertainment"],
    badges: ["Educational"],
    category: "Entertainment",
    status: "Open Now",
    rating: 4.7,
  },
];

// tagsAndCategories.js
export const AVAILABLE_TAGS = [
  "park",
  "nature",
  "recreation",
  "food",
  "shopping",
  "entertainment",
  "history",
  "landmark",
  "religious",
  "architecture",
  "education",
];
export const AVAILABLE_CATEGORIES = [
  "Parks",
  "Restaurants",
  "Shopping",
  "Entertainment",
  "Landmarks",
  "Religious",
];
